# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.15.0

steps:
  - block: "Start Code Freeze?"
    prompt: "Ready to cut the release branch from trunk?"

  - label: "Code Freeze"
    key: "code_freeze"
    command: |
      curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
      git config --global user.email "mobile@automattic.com"
      git config --global user.name "Buildkite"

      if [[ -z "${RELEASE_VERSION}" ]]; then
        echo "RELEASE_VERSION is not set."
        exit 1
      fi

      bundle install

      bundle exec fastlane code_freeze skip_confirm:true

  - block: "Complete Code Freeze?"
    depends_on: "code_freeze"
    prompt: |
      Be sure to verify that you have updated the libraries to a stable versions
      and that you've updated the Editorialized Release Notes
      (if they're available already) before continuing

  - label: "Completing Code Freeze"
    command: |
      curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
      git config --global user.email "mobile@automattic.com"
      git config --global user.name "Buildkite"

      bundle install

      bundle exec fastlane complete_code_freeze skip_confirm:true release_version:${RELEASE_VERSION}
