# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.15.0

steps:
  - label: "Code Freeze"
    plugins: *common_plugins
    command: |
      .buildkite/commands/configure-git.sh

      install_gems

      bundle exec fastlane code_freeze skip_confirm:true
