# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.15.0

steps:
  - label: "Finalize release"
    command: |
      curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
      git config --global user.email "mobile@automattic.com"
      git config --global user.name "Buildkite"

      bundle install

      bundle exec fastlane finalize_release
