UI.user_error!('Please run fastlane via `bundle exec`') unless FastlaneCore::Helper.bundler?

PROJECT_ROOT_FOLDER = File.dirname(File.expand_path(__dir__))
FASTLANE_FOLDER = File.join(PROJECT_ROOT_FOLDER, 'fastlane')

########################################################################
# Environment
########################################################################
fastlane_require 'dotenv'

Dotenv.load('~/.release-toolkit-demo-env.default')
ENV[GHHELPER_REPO = 'wordpress-mobile/release-toolkit-demo']
ENV['PROJECT_ROOT_FOLDER'] = File.dirname(File.expand_path(__dir__)) + '/'
ENV['FL_RELEASE_TOOLKIT_DEFAULT_BRANCH'] = 'trunk'

default_platform(:android)

platform :android do
  desc "Creates a new release branch from the current trunk"
  lane :code_freeze do | options |
    android_codefreeze_prechecks(skip_confirm: options[:skip_confirm])

    android_bump_version_release()
    new_version = android_get_app_version()

    setbranchprotection(repository: GHHELPER_REPO, branch: "release/#{new_version}")
    setfrozentag(repository: GHHELPER_REPO, milestone: new_version)
  end

  lane :complete_code_freeze do |options|
    android_completecodefreeze_prechecks(skip_confirm: options[:skip_confirm])

    ensure_git_status_clean
    push_to_git_remote
  end

  lane :trigger_code_freeze_in_ci do |options|
    buildkite_trigger_build(
      buildkite_organization: 'automattic',
      buildkite_pipeline: 'release-toolkit-demo',
      branch: 'trunk',
      pipeline_file: 'code-freeze.yml',
      message: 'Code Freeze in CI',
      environment: { CODE_FREEZE_VERSION: options[:code_freeze_version] }
    )
  end
end

